### ISSUE TITLE
GitHub Pages beállítása

### ISSUE THREAD

**Issue by Jabezare** [Teaching-projects/SZE-MOSZE-2020-Runtime_Terror#5]
Szeretném kérni a github pages beállítások módosítását, mert nekem nincsen hozzá jogosultságom. A gh-pages branch tartalmát szeretném megjeleníteni az oldalon.

**Comment by hegyhati** [comment]
`gh-pages/root`-ra beallitottam. Ha igy jo, akkor lezarhatod az issue-t.
